In [2]:
import pandas as pd
from tabula import read_pdf
from tabulate import tabulate

In [3]:
chlorpdf = read_pdf("../data/WildOnes/PHYTOREMEDIATION OF CHLORINATED SOLVENTS.pdf", pages = "all", multiple_tables=True)

In [5]:
pd.read_csv("../data/Prairie Moon/PM_Forbs.csv")

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,SEED $,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,BLOOM TIME,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 31,Unnamed: 32,*=recommended for landscaping; **=landscaping but aggressive
0,GENUS,species,Common Name,seeds/oz,seeds/pkt,pkt$,1/8 oz,1/4 oz,1/2 oz,oz,...,April,May,June,July,Aug,Sept,Oct,color,height,Comments
1,ACORUS,americanus,Sweet Flag,"6,600",100,$2.50,$3.00,$4.00,$6.50,$10.00,...,NaN,M,J,J,NaN,NaN,NaN,Grn,2',"Rhizomatous, Deer Resistant"
2,ACTAEA,pachypoda,Doll’s Eyes,"5,200",50,$2.50,$15.00,$25.00,NaN,NaN,...,NaN,M,J,NaN,NaN,NaN,NaN,Wht,2',"Difficult from Seed, White Fruit, poison, *,De..."
3,ACTAEA,rubra,Red Baneberry,"4,450",40,$2.50,$12.50,$20.00,$35.00,$60.00,...,A,M,NaN,NaN,NaN,NaN,NaN,Wht,2',"Difficult from Seed, Red Fruit, poison, *,Deer..."
4,AGALINIS,aspera,Rough False Foxglove,"100,000",700,$2.50,$17.50,$30.00,$55.00,$100.00,...,NaN,NaN,NaN,NaN,A,S,NaN,Pnk,2’,Annual
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
408,VIOLA,pedatifida,Prairie Violet,"28,000",100,NaN,NaN,NaN,NaN,NaN,...,A,M,J,NaN,NaN,NaN,NaN,Pur,7”,*
409,VIOLA,sororia,Common Blue Violet,"23,000",50,NaN,NaN,NaN,NaN,NaN,...,A,M,J,NaN,NaN,NaN,NaN,Pur,"4""","Pollinator Favorite ,Deer Resistant, *"
410,WULFENIA,bullii,Kittentails,"80,000",100,$2.50,$30.00,$55.00,NaN,NaN,...,NaN,M,NaN,NaN,NaN,NaN,NaN,Yel,"8""",NaN
411,ZIZIA,aptera,Heart-leaf Golden Alexanders,"12,000",150,$2.50,$7.50,$12.00,NaN,NaN,...,A,M,NaN,NaN,NaN,NaN,NaN,Yel,2',"Pollinator Favorite, *"
412,ZIZIA,aurea,Golden Alexanders,"11,000",150,$2.50,$3.00,$4.80,$7.80,$12.00,...,A,M,J,NaN,NaN,NaN,NaN,Yel,3',"Pollinator Favorite, *"