In [1]:
import pandas as pd

In [2]:
pm_inv = pd.read_csv('../data/output csv/pm_inv_uses.csv')

In [3]:
pm_inv = pm_inv.dropna(subset = ['air','heavy_metals','chlor_solv','lead(pb)','pesticides','petrol'], how = 'all')

In [4]:
sites = pd.read_csv('../data/output csv/sites_df2.csv')

In [5]:
pm_inv = pm_inv.fillna(0)
sites = sites.fillna(0)

In [6]:
pm_inv = pm_inv.rename(columns = {'heavy_metals':'HM','chlor_solv':'chlor','lead(pb)':'Pb','pesticides':'pest'})

In [7]:
pm_inv.head()

,genus,genus_species,common_name,plant_type,air,HM,chlor,Pb,pest,petrol
139,Eupatorium,Eupatorium altissimum,Tall Boneset,Forbs,0,hm(genus),0,0,0,0
140,Eupatorium,Eupatorium hyssopifolium,Hyssop-leaved Thoroughwort,Forbs,0,hm(genus),0,0,0,0
141,Eupatorium,Eupatorium perfoliatum,Boneset,Forbs,0,hm(genus),0,0,0,0
142,Eupatorium,Eupatorium serotinum,Late Boneset,Forbs,0,hm(genus),0,0,0,0
172,Helianthus,Helianthus angustifolius,Swamp Sunflower,Forbs,0,hm(genus),0,0,0,petrol(genus)

In [8]:
site_suggest = pm_inv.assign(ag = '', auto = '', paint = '', dryclean = '', golf = '', industrial = '', parking = '', rr = '', road = '', residential = '', utility = '', fire = '')

In [9]:
site_suggest

,genus,genus_species,common_name,plant_type,air,HM,chlor,Pb,pest,petrol,...,paint,dryclean,golf,industrial,parking,rr,road,residential,utility,fire
139,Eupatorium,Eupatorium altissimum,Tall Boneset,Forbs,0,hm(genus),0,0,0,0,...,,,,,,,,,,
140,Eupatorium,Eupatorium hyssopifolium,Hyssop-leaved Thoroughwort,Forbs,0,hm(genus),0,0,0,0,...,,,,,,,,,,
141,Eupatorium,Eupatorium perfoliatum,Boneset,Forbs,0,hm(genus),0,0,0,0,...,,,,,,,,,,
142,Eupatorium,Eupatorium serotinum,Late Boneset,Forbs,0,hm(genus),0,0,0,0,...,,,,,,,,,,
172,Helianthus,Helianthus angustifolius,Swamp Sunflower,Forbs,0,hm(genus),0,0,0,petrol(genus),...,,,,,,,,,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,Spartina,Spartina pectinata,Cord Grass Pls,Grasses-Sedges-Rushes,0,hm,0,0,0,petrol,...,,,,,,,,,,
541,Amorpha,Amorpha canescens,Lead Plant,Shrubs-Vines,0,hm(genus),0,pb(genus),0,0,...,,,,,,,,,,
542,Amorpha,Amorpha fruticosa,False Indigo,Shrubs-Vines,0,hm,0,pb,0,0,...,,,,,,,,,,
543,Amorpha,Amorpha nana,Fragrant False Indigo,Shrubs-Vines,0,hm(genus),0,pb(genus),0,0,...,,,,,,,,,,
553,Physocarpus,Physocarpus opulifolius,Prairie Ninebark,Shrubs-Vines,air,0,0,0,0,0,...,,,,,,,,,,

In [10]:
site_suggest.columns

Index(['genus', 'genus_species', 'common_name', 'plant_type', 'air', 'HM',
       'chlor', 'Pb', 'pest', 'petrol', 'ag', 'auto', 'paint', 'dryclean',
       'golf', 'industrial', 'parking', 'rr', 'road', 'residential', 'utility',
       'fire'],
      dtype='object')

In [11]:
sites

,pollutant,agriculture,autobody shop,old building,dry cleaner,golf course,industrial site,orchard,parking lot,railroad,roadway,smelting,tannery,residential,utility,wildfire
0,air,0,0,0,0,0,air,0,0,air,0,0,0,air,0,air
1,chlor,0,chlor,0,chlor,0,chlor,0,0,chlor,0,0,0,0,0,0
2,HM,HM,0,HM,0,0,HM,0,0,0,HM,HM,HM,0,0,0
3,Pb,0,0,Pb,0,0,0,0,0,0,Pb,0,0,0,0,0
4,pest,pest,0,0,0,pest,0,pest,0,pest,0,0,0,pest,pest,0
5,petrol,0,petrol,0,0,0,0,0,petrol,petrol,petrol,0,0,petrol,0,0

In [12]:
for row_value, row_index in site_suggest.iterrows():
    
    if row_index['HM'] != 0 and row_index['pest'] != 0:
        site_suggest.at[row_value,'ag'] = 'all'
    elif row_index['HM'] != 0 or row_index['pest'] != 0:
        site_suggest.at[row_value,'ag'] = '1+'
        
    if row_index['chlor'] != 0 and row_index['petrol'] != 0:
        site_suggest.at[row_value,'auto'] = 'all'
    elif row_index['chlor'] != 0 or row_index['petrol'] != 0:
        site_suggest.at[row_value,'auto'] = '1+'
        
    if row_index['Pb'] != 0:
        site_suggest.at[row_value,'paint'] = 'all'
    
    if row_index['chlor'] != 0:
        site_suggest.at[row_value,'dryclean'] = 'all'
    
    if row_index['pest'] != 0:
        site_suggest.at[row_value,'golf'] = 'all'
        site_suggest.at[row_value,'utility'] = 'all'

    if row_index['air'] != 0 and row_index['chlor'] != 0 and row_index['HM'] != 0:
        site_suggest.at[row_value,'industrial'] = 'all'
    elif row_index['air'] != 0 or row_index['chlor'] != 0 or row_index['HM'] != 0:    
        site_suggest.at[row_value,'industrial'] = '1+'
        
    if row_index['petrol'] != 0:
        site_suggest.at[row_value,'parking'] = 'all'
    
    if row_index['air'] != 0 and row_index['chlor'] != 0 and row_index['pest'] != 0 and row_index['petrol'] != 0:
        site_suggest.at[row_value,'rr'] = 'all'
    elif row_index['air'] != 0 or row_index['chlor'] != 0 or row_index['pest'] != 0 or row_index['petrol'] != 0:
        site_suggest.at[row_value,'rr'] = '1+'
        
    if row_index['Pb'] != 0 and row_index['petrol'] != 0:
        site_suggest.at[row_value,'road'] = 'all'
    elif row_index['Pb'] != 0 or row_index['petrol'] != 0:
        site_suggest.at[row_value,'road'] = '1+'
    
    if row_index['air'] != 0 and row_index['pest'] != 0 and row_index['petrol'] != 0:
        site_suggest.at[row_value,'residential'] = 'all'
    elif row_index['air'] != 0 or row_index['pest'] != 0 or row_index['petrol'] != 0:
        site_suggest.at[row_value,'residential'] = '1+'    
        
    if row_index['air'] != 0:
        site_suggest.at[row_value,'fire'] = 'all'

In [13]:
site_suggest

,genus,genus_species,common_name,plant_type,air,HM,chlor,Pb,pest,petrol,...,paint,dryclean,golf,industrial,parking,rr,road,residential,utility,fire
139,Eupatorium,Eupatorium altissimum,Tall Boneset,Forbs,0,hm(genus),0,0,0,0,...,,,,1+,,,,,,
140,Eupatorium,Eupatorium hyssopifolium,Hyssop-leaved Thoroughwort,Forbs,0,hm(genus),0,0,0,0,...,,,,1+,,,,,,
141,Eupatorium,Eupatorium perfoliatum,Boneset,Forbs,0,hm(genus),0,0,0,0,...,,,,1+,,,,,,
142,Eupatorium,Eupatorium serotinum,Late Boneset,Forbs,0,hm(genus),0,0,0,0,...,,,,1+,,,,,,
172,Helianthus,Helianthus angustifolius,Swamp Sunflower,Forbs,0,hm(genus),0,0,0,petrol(genus),...,,,,1+,all,1+,1+,1+,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
531,Spartina,Spartina pectinata,Cord Grass Pls,Grasses-Sedges-Rushes,0,hm,0,0,0,petrol,...,,,,1+,all,1+,1+,1+,,
541,Amorpha,Amorpha canescens,Lead Plant,Shrubs-Vines,0,hm(genus),0,pb(genus),0,0,...,all,,,1+,,,1+,,,
542,Amorpha,Amorpha fruticosa,False Indigo,Shrubs-Vines,0,hm,0,pb,0,0,...,all,,,1+,,,1+,,,
543,Amorpha,Amorpha nana,Fragrant False Indigo,Shrubs-Vines,0,hm(genus),0,pb(genus),0,0,...,all,,,1+,,,1+,,,
553,Physocarpus,Physocarpus opulifolius,Prairie Ninebark,Shrubs-Vines,air,0,0,0,0,0,...,,,,1+,,1+,,1+,,all

In [14]:
#site_suggest.to_csv('../data/output csv/site_suggest.csv', header = True, index = False)